spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

server:
  servlet:
    session:
      cookie:
        secure: false  # 개발서버에서는 HTTP 허용

app:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:8080"
      - "https://web-muneo-fe-m3d8djgv98deef95.sel4.cloudtype.app"

logging:
  level:
    org.hibernate.SQL: debug
    ureca: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.transaction: debug