spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    ureca: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.transaction: debug