spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  servlet:
    session:
      cookie:
        secure: true  # 개발서버에서는 HTTP 허용
        same-site: none

logging:
  level:
    org.hibernate.SQL: debug
    ureca: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.transaction: debug